logger_name: street_common_lane
edges:
  - [Pose_50, Pose_53]
  - [Pose_53, Pose_251]
  - [Pose_73, Pose_193]
  - [Pose_72, stairs_mensa]
  - [Pose_74, Pose_251]
  - [Pose_193, Pose_79]
  - [Pose_195, Pose_99]
  - [INT-A1, Pose_90]
  - [Pose_90, Pose_96]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
