logger_name: street_connection_lane
edges:
  - [Pose 51, Pose 52]
  - [Pose 54, Pose 55]
  - [Pose 85, Pose 87]
  - [Pose 201, INT-A1]
  - [Pose 97, Pose 96]
  - [Pose 96, Pose 100]
  - [Pose 93, Pose 95]
base_dir: 'angela'
event_radius: 0.5
event_threshold: 0.1
min_distance_static_samples: 0.5
