logger_name: street_common_lane
edges:
  - [Pose 51, Pose 52]
  - [Pose 54, Pose 55]
  - [Pose 194, Pose 74]
  - [Pose 193, Pose 73]
  - [Pose 85, Pose 87]
  - [Pose 202, Pose 86]
  - [Pose 201, INT-A1]
  - [Pose 97, Pose 96]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
