logger_name: street_connection_lane
edges:
  - [LC-054, C002]
  - [LA-002, A-stairs-main]
  - [INT-A001, LA-011]
  - [LA-017, LA-018]
  - [A045, LA-019]
  - [LA-016, LA-017]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
