logger_name: street_left_lane
nodes:
edges:
  - [Pose 50, Pose 52]
  - [Pose 52, Pose 53]
  - [Pose 251, Pose 55]
  - [Pose 55, Pose 74]
  - [Pose 74, Pose 73]
  - [Pose 73, Pose 72]
  - [Pose 72, Pose 75]
  - [Pose 75, Pose 77]
  - [stairs_mensa, Pose 77]
  - [Pose 193, stairs_mensa]
  - [stairs_mensa, Pose 79]
  - [Pose 79, Pose 77]
  - [Pose 77, Pose 81]
  - [Pose 81, Pose 252]
  - [Pose 252, Pose 195]
  - [Pose 99, Pose 83]
  - [Pose 83, Pose 88]
  - [Pose 88, Pose 87]
  - [Pose 87, INT-A1]
  - [Pose 96, Pose 95]
  - [Pose 95, street_end]
  - [street_end, Pose 94]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
