logger_name: street_left_lane
nodes:
edges:
  - [Pose_50, Pose_52]
  - [Pose_52, Pose_53]
  - [Pose_251, Pose_55]
  - [Pose_55, Pose_74]
  - [Pose_74, Pose_73]
  - [Pose_73, Pose_72]
  - [Pose_72, Pose_75]
  - [Pose_75, Pose_77]
  - [stairs_mensa, Pose_77]
  - [Pose_193, stairs_mensa]
  - [stairs_mensa, Pose_79]
  - [Pose_79, Pose_77]
  - [Pose_77, Pose_81]
  - [Pose_81, Pose_252]
  - [Pose_252, Pose_195]
  - [Pose_99, Pose_83]
  - [Pose_83, Pose_88]
  - [Pose_88, Pose_87]
  - [Pose_87, INT-A1]
  - [Pose_96, Pose_95]
  - [Pose_95, street_end]
  - [street_end, Pose_94]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
