logger_name: street_left_lane
edges:
  - [INT-C002, LC-054]
  - [LC-054, INT-C007]
  - [LA-001, LA-002]
  - [LA-002, A-main-entrance]
  - [A-main-entrance, LA-004]
  - [LA-004, A-elevator-1]
  - [LA-004, LA-005]
  - [A-elevator-1, A-atm]
  - [A-atm, LA-006]
  - [stairs-mensa, mensa-entrance]
  - [mensa-entrance, LA-006]
  - [LA-006, A-cafeteria]
  - [A-cafeteria, LA-009]
  - [LA-009, LA-022]
  - [LA-022, A049]
  - [A049, A053]
  - [A053, A054]
  - [A053, LA-014]
  - [A054, INT-A001]
  - [INT-A001, LA-015]
  - [LA-015, LA-017]
  - [LA-017, A045]
  - [A045, street-end]
  - [street-end, LA-020]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
