logger_name: street_right_lane
edges:
  - [Pose_50, Pose_51]
  - [Pose_51, Pose_53]
  - [Pose_251, Pose_54]
  - [Pose_54, Pose_74]
  - [Pose_74, Pose_194]
  - [Pose_194, Pose_193]
  - [Pose_79, Pose_76]
  - [Pose_76, Pose_80]
  - [Pose_80, Pose_245]
  - [Pose_245, Pose_99]
  - [Pose_99, Pose_82]
  - [Pose_82, Pose_84]
  - [Pose_84, Pose_85]
  - [Pose_85, Pose_201]
  - [Pose_201, Pose_90]
  - [Pose_90, Pose_100]
  - [Pose_100, Pose_97]
  - [Pose_97, Pose_93]
  - [Pose_93, Pose_95]
  - [street_end, Pose_92]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
