logger_name: street_right_lane
edges:
  - [Pose 50, Pose 51]
  - [Pose 51, Pose 53]
  - [Pose 251, Pose 54]
  - [Pose 54, Pose 74]
  - [Pose 74, Pose 194]
  - [Pose 194, Pose 193]
  - [Pose 79, Pose 76]
  - [Pose 76, Pose 80]
  - [Pose 80, Pose 245]
  - [Pose 245, Pose 99]
  - [Pose 99, Pose 82]
  - [Pose 82, Pose 84]
  - [Pose 84, Pose 85]
  - [Pose 85, Pose 201]
  - [Pose 201, Pose 90]
  - [Pose 90, Pose 100]
  - [Pose 100, Pose 97]
  - [Pose 97, Pose 93]
  - [Pose 93, Pose 95]
  - [street_end, Pose 92]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
