right_lane:
  edges:
    - [44, 84]
    - [84, 45]
    - [45, 48]
    - [48, 49]
    - [49, 40]
    - [40, 83]
    - [83, 39]
    - [39, 36]
    - [36, 35]
    - [35, 82]
    - [82, 32]
    - [32, 29]
    - [29, 31]
    - [29, 27]
    - [27, 81]
    - [81, 26]
    - [26, 22]
    - [22, 21]
    - [21, 18]
    - [18, 93]
    - [26, 286]
    - [286, 93]
    - [93, 80]
    - [80, 73]
    - [73, 75]
    - [75, 76]
    - [76, 91]
    - [119, 120]
    - [120, 196]
    - [196, 122]
    - [262, 260]
    - [260, 259]
    - [259, 257]
    - [257, 252]
    - [252, 250]
    - [250, 248]
    - [248, 247]
    - [247, 245]
    - [75, 72]
    - [72, 90]
    - [90, 70]
    - [70, 68]
    - [68, 89]
    - [89, 66]
    - [66, 64]
    - [64, 62]
    - [64, 56]
    - [56, 86]
    - [86, 55]
    - [55, 53]
    - [53, 85]
    - [85, 51]
    - [51, 49]
    - [49, 42]
    - [64, 61]
    - [81, 87]
    - [87, 59]
  base_dir: 'osm'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
left_lane:
  edges:
    - [84, 46]
    - [46, 47]
    - [47, 49]
    - [49, 41]
    - [41, 83]
    - [83, 38]
    - [38, 37]
    - [37, 34]
    - [34, 82]
    - [82, 33]
    - [33, 29]
    - [29, 30]
    - [29, 28]
    - [28, 81]
    - [26, 24]
    - [24, 16]
    - [16, 15]
    - [15, 93]
    - [26, 285]
    - [285, 93]
    - [80, 74]
    - [74, 75]
    - [75, 77]
    - [77, 91]
    - [117, 265]
    - [265, 264]
    - [264, 262]
    - [262, 261]
    - [261, 259]
    - [259, 258]
    - [258, 252]
    - [252, 251]
    - [251, 249]
    - [249, 247]
    - [247, 246]
    - [75, 71]
    - [71, 90]
    - [90, 69]
    - [69, 67]
    - [67, 89]
    - [89, 65]
    - [65, 64]
    - [64, 57]
    - [64, 63]
    - [57, 86]
    - [86, 54]
    - [54, 52]
    - [52, 85]
    - [85, 50]
    - [50, 49]
    - [49, 43]
    - [64, 60]
    - [60, 88]
    - [88, 58]
  base_dir: 'osm'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
connection_lane:
  edges:
    - [46, 45]
    - [26, 23]
    - [23, 20]
    - [20, 19]
    - [19, 93]
    - [26, 25]
    - [25, 17]
    - [17, 14]
    - [14, 93]
    - [63, 62]
    - [56, 57]
    - [87, 60]
    - [61, 60]
    - [61, 88]
    - [118, 266]
    - [266, 263]
    - [246, 245]
  base_dir: 'osm'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
bidder_radius_2:
  edges:
    - [91, 117]
    - [117, 118]
    - [118, 119]
    - [119, 263]
    - [263, 262]
  base_dir: 'osm'
  event_radius: 2
  event_threshold: 0.1
  min_distance_static_samples: 0.5
