one_lane:
  edges:
    - [c022, square_inter_1]
    - [square_inter_1, square_inter_2]
    - [square_inter_2, square_inter_3]
    - [square_inter_3, c022]
    - [square_inter_1, atm]
    - [atm, stairs_mensa]
    - [stairs_mensa, street_end]
    - [street_end, faraway_end]
  base_dir: 'ethan'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
