c022: [-0.71, -2.33, 0]
square_inter_1: [-31.5, -49, 0]
square_inter_2: [-60, -30, 0]
square_inter_3: [-37.5, 5, 0]
atm: [-13, -70, 0]
stairs_mensa: [-14, -75, 0]
street_end: [-63, -145, 0]
faraway_end: [-67, 18.5, 0]