faraway_common_lane:
  edges:
    - [INT-B001, LB-015]
    - [LB-015, LB-017]
    - [LB-017, INT-B001]
    - [INT-B001, LB-016]
    - [LB-016, LB-018]
    - [INT-B002, LB-027]
    - [LB-027, LB-029]
    - [INT-B002, LB-028]
    - [INT-B002, LB-030]
    - [INT-B003, LB-042]
    - [LB-042, LB-044]
    - [INT-B003, LB-043]
    - [INT-B003, LB-045]
    - [INT-B004, LB-061]
    - [INT-B004, LB-062]
    - [LB-061, LB-062]
    - [INT-B005, LB-067]
    - [LB-067, LB-069]
    - [INT-B005, LB-068]
    - [INT-B005, LB-070]
  base_dir: 'angela'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
faraway_connection_lane:
  edges:
    - [LB-002, LB-001]
    - [B006, B001]
    - [B008-1, B003]
    - [B008-2, B005]
    - [B012, B007-1]
    - [B010, B007-1]
    - [B014-1, B007-2]
    - [B014-1, B009]
    - [B014-2, B011]
    - [LB-019, B015]
    - [B016-1, B017]
    - [B016-2, B019]
    - [B002, LB-022]
    - [B018, B021]
    - [LB-025, B025]
    - [B022, LB-026]
    - [B024, B027]
    - [LB-031, B029]
    - [B032, B031]
    - [B034, B033]
    - [LB-034, B035]
    - [B036, B037]
    - [B038-1, B039]
    - [B038-2, B041]
    - [LB-040, LB-041]
    - [B044-1, B045]
    - [B044-2, B047]
    - [LB-050, B049]
    - [B050-1, B051]
    - [B050-2, B053]
    - [LB-057, B055]
    - [LB-057, B057]
    - [LB-059, LB-060]
    - [B060-1, B061]
    - [B060-2, B063]
    - [B062, B065]
    - [B064, B067]
  base_dir: 'angela'
  event_radius: 0.3
  event_threshold: 0.1
  min_distance_static_samples: 0.5
faraway_left_lane:
  edges:
    - [LA-020, LB-001]
    - [LB-001, B001]
    - [B001, B003]
    - [B003, B005]
    - [B005, B007-1]
    - [B007-1, B007-2]
    - [B007-2, B009]
    - [B009, B011]
    - [B011, INT-B001]
    - [INT-B001, B015]
    - [B015, B017]
    - [B017, B019]
    - [B019, LB-022]
    - [LB-022, B021]
    - [B021, B025]
    - [B025, LB-026]
    - [LB-026, B027]
    - [B027, INT-B002]
    - [INT-B002, B029]
    - [B029, B031]
    - [B031, B033]
    - [B033, B035]
    - [B035, B037]
    - [B037, B039]
    - [B039, B041]
    - [B041, LB-041]
    - [LB-041, INT-B003]
    - [INT-B003, B045]
    - [B045, B047]
    - [B047, B049]
    - [B049, B051]
    - [B051, B053]
    - [B053, B055]
    - [B055, B057]
    - [B057, LB-060]
    - [LB-060, INT-B004]
    - [INT-B004, B061]
    - [B061, B063]
    - [B063, B065]
    - [B065, B067]
    - [B067, INT-B005]
  base_dir: 'angela'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
faraway_right_lane:
  edges:
    - [LA-020, LB-002]
    - [LB-002, B006]
    - [B006, B008-1]
    - [B008-1, B008-2]
    - [B008-2, B012]
    - [B012, B010]
    - [B010, B014-1]
    - [B014-1, B014-2]
    - [B014-2, INT-B001]
    - [INT-B001, LB-019]
    - [LB-019, B016-1]
    - [B016-1, B016-2]
    - [B016-2, B002]
    - [B002, B018]
    - [B018, LB-025]
    - [LB-025, B022]
    - [B022, B024]
    - [B024, INT-B002]
    - [INT-B002, LB-031]
    - [LB-031, B032]
    - [B032, B034]
    - [B034, LB-034]
    - [LB-034, B036]
    - [B036, B038-1]
    - [B038-1, B038-2]
    - [B038-2, LB-040]
    - [LB-040, INT-B003]
    - [INT-B003, B044-1]
    - [B044-1, B044-2]
    - [B044-2, LB-050]
    - [LB-050, B048]
    - [B048, B046]
    - [B046, B050-1]
    - [B050-1, B050-2]
    - [B050-2, LB-057]
    - [LB-057, LB-059]
    - [LB-059, INT-B004]
    - [INT-B004, B060-1]
    - [B060-1, B060-2]
    - [B060-2, B062]
    - [B062, B064]
    - [B064, INT-B005]
  base_dir: 'angela'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
square_common_lane:
  edges:
    - [INT-C004, LC-036]
    - [LC-036, LC-037]
    - [LC-037, LC-038]
    - [LC-038, LC-039]
    - [INT-C005, INT-C009]
  base_dir: 'angela'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
square_connection_lane:
  edges:
    - [C022, C025]
    - [LC-001, LC-002]
    - [C018-1, C021]
    - [C018-2, C019]
    - [LC-007, C017]
    - [C016-1, LC-010]
    - [LC-003, C015]
    - [C016-2, LC-004]
    - [C014-1, C013-1]
    - [LC-005, C013-2]
    - [C014-2, LC-006]
    - [C012, LC-015]
    - [LC-016, LC-017]
    - [LC-022, LC-023]
    - [LC-024, LC-025]
    - [LC-026, C059]
    - [C058, C061-2]
    - [C060, C061-1]
    - [LC-031, C063-2]
    - [C062, LC-008]
    - [LC-009, C063-1]
    - [C064, C065]
    - [LC-034, LC-035]
    - [LC-041, C067]
    - [LC-043, LC-044]
    - [C066, LC-046]
    - [LC-047, LC-048]
    - [LC-039, C069-2]
    - [C070, LC-040]
    - [C072, C069-1]
    - [LC-049, LC-050]
    - [LC-051, LC-052]
  base_dir: 'angela'
  event_radius: 0.3
  event_threshold: 0.1
  min_distance_static_samples: 0.5
square_left_lane:
  edges:
    - [C020, LC-001]
    - [LC-001, INT-C001]
    - [INT-C001, C018-1]
    - [C018-1, C018-2]
    - [C018-2, LC-007]
    - [LC-007, C016-1]
    - [C016-1, LC-003]
    - [LC-003, C016-2]
    - [C016-2, C014-1]
    - [C014-1, LC-005]
    - [LC-005, C014-2]
    - [C014-2, C012]
    - [C012, INT-C002]
    - [INT-C002, LC-016]
    - [LC-016, C-stairs-1]
    - [C-stairs-1, LC-018]
    - [LC-018, LC-020]
    - [LC-020, C-stairs-2]
    - [C-stairs-2, LC-022]
    - [LC-022, INT-C003]
    - [INT-C003, C059]
    - [INT-C003, LC-024]
    - [C059, C061-2]
    - [C061-2, C061-1]
    - [C061-1, C063-2]
    - [C063-2, LC-008]
    - [LC-008, C063-1]
    - [C063-1, C065]
    - [C065, LC-035]
    - [LC-035, INT-C004]
    - [INT-C004, C066]
    - [C066, LC-047]
    - [LC-047, INT-C005]
    - [INT-C009, LC-049]
    - [LC-049, INT-C001]
    - [INT-C001, LC-051]
    - [LC-038, C069-2]
    - [LC-039, LC-040]
    - [C070, C069-1]
    - [C020, C022]
  base_dir: 'angela'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
square_right_lane:
  edges:
    - [C020, LC-002]
    - [LC-002, INT-C001]
    - [INT-C001, C021]
    - [C021, C019]
    - [C019, C017]
    - [C017, LC-010]
    - [LC-010, C015]
    - [C015, LC-004]
    - [LC-004, C013-1]
    - [C013-1, C013-2]
    - [C013-2, LC-006]
    - [LC-006, LC-015]
    - [LC-015, INT-C002]
    - [INT-C002, LC-017]
    - [LC-017, C-stairs-1]
    - [C-stairs-1, LC-019]
    - [LC-019, LC-021]
    - [LC-021, C-stairs-2]
    - [C-stairs-2, LC-023]
    - [LC-023, INT-C003]
    - [INT-C003, LC-026]
    - [INT-C003, LC-025]
    - [LC-026, C058]
    - [C058, C060]
    - [C060, LC-031]
    - [LC-031, C062]
    - [C062, LC-009]
    - [LC-009, C064]
    - [C064, LC-034]
    - [LC-034, INT-C004]
    - [INT-C004, LC-046]
    - [LC-046, LC-048]
    - [LC-048, INT-C005]
    - [INT-C004, LC-044]
    - [LC-044, C067]
    - [INT-C009, LC-050]
    - [LC-050, INT-C001]
    - [INT-C001, LC-052]
    - [LC-039, C070]
    - [C070, C072]
    - [C020, C025]
  base_dir: 'angela'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
street_common_lane:
  edges:
    - [INT-C002, INT-C007]
    - [INT-C007, LA-001]
    - [stairs-mensa, LA-006]
    - [LA-001, A-main-entrance]
    - [LA-005, stairs-mensa]
    - [A-elevator-1, stairs-mensa]
    - [LA-005, mensa-entrance]
    - [LA-005, stairs-mensa]
  base_dir: 'angela'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
street_connection_lane:
  edges:
    - [LC-054, C002]
    - [LA-002, A-stairs-main]
    - [INT-A001, LA-011]
    - [LA-017, LA-018]
    - [A045, LA-019]
    - [LA-016, LA-017]
  base_dir: 'angela'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
street_left_lane:
  edges:
    - [INT-C002, LC-054]
    - [LC-054, INT-C007]
    - [LA-001, LA-002]
    - [LA-002, A-main-entrance]
    - [A-main-entrance, LA-004]
    - [LA-004, A-elevator-1]
    - [LA-004, LA-005]
    - [A-elevator-1, A-atm]
    - [A-atm, LA-006]
    - [stairs-mensa, mensa-entrance]
    - [mensa-entrance, LA-006]
    - [LA-006, A-cafeteria]
    - [A-cafeteria, LA-009]
    - [LA-009, LA-022]
    - [LA-022, A049]
    - [A049, A053]
    - [A053, A054]
    - [A053, LA-014]
    - [A054, INT-A001]
    - [INT-A001, LA-015]
    - [LA-015, LA-017]
    - [LA-017, A045]
    - [A045, street-end]
    - [street-end, LA-020]
  base_dir: 'angela'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
street_right_lane:
  edges:
    - [INT-C002, C002]
    - [C002, INT-C007]
    - [LA-001, A-stairs-main]
    - [A-stairs-main, A-main-entrance]
    - [A-main-entrance, LA-003]
    - [LA-003, LA-005]
    - [mensa-entrance, LA-007]
    - [LA-007, LA-008]
    - [LA-008, LA-010]
    - [LA-010, LA-022]
    - [LA-022, LA-012]
    - [LA-012, LA-013]
    - [LA-013, LA-014]
    - [LA-014, LA-011]
    - [LA-011, LA-015]
    - [LA-015, LA-016]
    - [LA-016, LA-018]
    - [LA-018, LA-019]
    - [street-end, LA-021]
  base_dir: 'angela'
  event_radius: 1
  event_threshold: 0.1
  min_distance_static_samples: 0.5
