logger_name: faraway_common_lane
edges:
  - [INT-B001, LB-015]
  - [LB-015, LB-017]
  - [LB-017, INT-B001]
  - [INT-B001, LB-016]
  - [LB-016, LB-018]
  - [INT-B002, LB-027]
  - [LB-027, LB-029]
  - [INT-B002, LB-028]
  - [INT-B002, LB-030]
  - [INT-B003, LB-042]
  - [LB-042, LB-044]
  - [INT-B003, LB-043]
  - [INT-B003, LB-045]
  - [INT-B004, LB-061]
  - [INT-B004, LB-062]
  - [LB-061, LB-062]
  - [INT-B005, LB-067]
  - [LB-067, LB-069]
  - [INT-B005, LB-068]
  - [INT-B005, LB-070]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
