logger_name: faraway_connection_lane
edges:
  - [Pose 103 , Pose 104]
  - [Pose 102 , Pose 101]
  - [Pose 110 , Pose 111]
  - [Pose 114 , Pose 113]
  - [Pose 113 , Pose 108]
  - [Pose 108 , Pose 109]
  - [Pose 112 , Pose 234]
  - [Pose 112, Pose 105]
  - [Pose 235 , Pose 105]
  - [Pose 107 , Pose 106]
  - [INT-B1 , Pose 118]
  - [INT-B1 , Pose 119]
  - [INT-B1 , Pose 115]
  - [Pose 115 , Pose 116]
  - [Pose 116 , INT-B1]
  - [Pose 123 , Pose 122]
  - [Pose 121 , Pose 120]
  - [Pose 126 , Pose 127]
  - [Pose 127 , Pose 124]
  - [Pose 127, Pose 125]
  - [Pose 124 , Pose 125]
  - [Pose 128, Pose 129]
  - [Pose 131 , Pose 130]
  - [Pose 132, Pose 133]
  - [Pose 132, Pose 136]
  - [Pose 132, Pose 134]
  - [Pose 134, Pose 135]
  - [Pose 135, Pose 132]
  - [Pose 137, Pose 138]
  - [Pose 139, Pose 140]
  - [Pose 141, Pose 143]
  - [Pose 230, Pose 229]
  - [Pose 229, Pose 142]
  - [Pose 144, Pose 145]
  - [Pose 148, Pose 149]
  - [Pose 147, Pose 146]
  - [Pose 158, Pose 157]
  - [Pose 156, Pose 155]
  - [Pose 160, Pose 159]
  - [Pose 164, Pose 163]
  - [Pose 163, Pose 162]
  - [Pose 162, Pose 161]
  - [Pose 161, Pose 163]
  - [Pose 163, Pose 164]
  - [Pose 166, Pose 165]
  - [Pose 168, Pose 167]
  - [Pose 170, Pose 169]
  - [INT-B2, Pose 171]
  - [Pose 171, Pose 172]
  - [Pose 172, INT-B2]
  - [Pose 175, Pose 174]
  - [Pose 177, Pose 176]
  - [Pose 179, Pose 178]
  - [Pose 183, Pose 182]
  - [Pose 181, Pose 180]
  - [Pose 185, Pose 184]
  - [Pose 187, Pose 186]
  - [INT-B3, Pose 189]
  - [Pose 189, Pose 190]
  - [INT-B3, Pose 190]
  - [INT-B3, Pose 191]
  - [Pose 191, Pose 192]
  - [Pose 192, INT-B3]
base_dir: 'angela'
event_radius: 0.3
event_threshold: 0.1
min_distance_static_samples: 0.5
