logger_name: faraway_connection_lane
edges:
  - [Pose_103 , Pose_104]
  - [Pose_102 , Pose_101]
  - [Pose_110 , Pose_111]
  - [Pose_114 , Pose_113]
  - [Pose_113 , Pose_108]
  - [Pose_108 , Pose_109]
  - [Pose_112 , Pose_234]
  - [Pose_112, Pose_105]
  - [Pose_235 , Pose_105]
  - [Pose_107 , Pose_106]
  - [INT-B1 , Pose_118]
  - [INT-B1 , Pose_119]
  - [INT-B1 , Pose_115]
  - [Pose_115 , Pose_116]
  - [Pose_116 , INT-B1]
  - [Pose_123 , Pose_122]
  - [Pose_121 , Pose_120]
  - [Pose_126 , Pose_127]
  - [Pose_127 , Pose_124]
  - [Pose_127, Pose_125]
  - [Pose_124 , Pose_125]
  - [Pose_128, Pose_129]
  - [Pose_131 , Pose_130]
  - [Pose_132, Pose_133]
  - [Pose_132, Pose_136]
  - [Pose_132, Pose_134]
  - [Pose_134, Pose_135]
  - [Pose_135, Pose_132]
  - [Pose_137, Pose_138]
  - [Pose_139, Pose_140]
  - [Pose_141, Pose_143]
  - [Pose_230, Pose_229]
  - [Pose_229, Pose_142]
  - [Pose_144, Pose_145]
  - [Pose_148, Pose_149]
  - [Pose_147, Pose_146]
  - [Pose_158, Pose_157]
  - [Pose_156, Pose_155]
  - [Pose_160, Pose_159]
  - [Pose_164, Pose_163]
  - [Pose_163, Pose_162]
  - [Pose_162, Pose_161]
  - [Pose_161, Pose_163]
  - [Pose_163, Pose_164]
  - [Pose_166, Pose_165]
  - [Pose_168, Pose_167]
  - [Pose_170, Pose_169]
  - [INT-B2, Pose_171]
  - [Pose_171, Pose_172]
  - [Pose_172, INT-B2]
  - [Pose_175, Pose_174]
  - [Pose_177, Pose_176]
  - [Pose_179, Pose_178]
  - [Pose_183, Pose_182]
  - [Pose_181, Pose_180]
  - [Pose_185, Pose_184]
  - [Pose_187, Pose_186]
  - [INT-B3, Pose_189]
  - [Pose_189, Pose_190]
  - [INT-B3, Pose_190]
  - [INT-B3, Pose_191]
  - [Pose_191, Pose_192]
  - [Pose_193, INT-B3]
base_dir: 'angela'
event_radius: 0.3
event_threshold: 0.1
min_distance_static_samples: 0.5
