logger_name: faraway_left_lane
edges:
  - [Pose_92, Pose_103]
  - [Pose_103, Pose_102]
  - [Pose_102, Pose_110]
  - [Pose_110, Pose_114]
  - [Pose_114, Pose_233]
  - [Pose_233, Pose_112]
  - [Pose_112, Pose_235]
  - [Pose_235, Pose_107]
  - [Pose_107, Pose_232]
  - [Pose_232, INT-B1]
  - [INT-B1, Pose_123]
  - [Pose_123, Pose_121]
  - [Pose_121, Pose_126]
  - [Pose_126, Pose_128]
  - [Pose_128, Pose_131]
  - [Pose_131, Pose_132]
  - [Pose_132, Pose_137]
  - [Pose_137, Pose_139]
  - [Pose_139, Pose_141]
  - [Pose_141, Pose_230]
  - [Pose_230, Pose_144]
  - [Pose_144, Pose_148]
  - [Pose_148, Pose_147]
  - [Pose_147, Pose_152]
  - [Pose_152, Pose_158]
  - [Pose_158, Pose_156]
  - [Pose_156, Pose_160]
  - [Pose_160, Pose_164]
  - [Pose_164, Pose_166]
  - [Pose_166, Pose_168]
  - [Pose_168, Pose_170]
  - [Pose_170, INT-B2]
  - [INT-B2, Pose_175]
  - [Pose_175, Pose_177]
  - [Pose_177, Pose_179]
  - [Pose_179, Pose_183]
  - [Pose_183, Pose_181]
  - [Pose_181, Pose_185]
  - [Pose_185, Pose_187]
  - [Pose_187, INT-B3]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
