logger_name: faraway_left_lane
edges:
  - [Pose 92, Pose 103]
  - [Pose 103, Pose 102]
  - [Pose 102, Pose 110]
  - [Pose 110, Pose 114]
  - [Pose 114, Pose 233]
  - [Pose 233, Pose 112]
  - [Pose 112, Pose 235]
  - [Pose 235, Pose 107]
  - [Pose 107, Pose 232]
  - [Pose 232, INT-B1]
  - [INT-B1, Pose 123]
  - [Pose 123, Pose 121]
  - [Pose 121, Pose 126]
  - [Pose 126, Pose 128]
  - [Pose 128, Pose 131]
  - [Pose 131, Pose 132]
  - [Pose 132, Pose 137]
  - [Pose 137, Pose 139]
  - [Pose 139, Pose 141]
  - [Pose 141, Pose 230]
  - [Pose 230, Pose 144]
  - [Pose 144, Pose 148]
  - [Pose 148, Pose 147]
  - [Pose 147, Pose 152]
  - [Pose 152, Pose 158]
  - [Pose 158, Pose 156]
  - [Pose 156, Pose 160]
  - [Pose 160, Pose 164]
  - [Pose 164, Pose 166]
  - [Pose 166, Pose 168]
  - [Pose 168, Pose 170]
  - [Pose 170, INT-B2]
  - [INT-B2, Pose 175]
  - [Pose 175, Pose 177]
  - [Pose 177, Pose 179]
  - [Pose 179, Pose 183]
  - [Pose 183, Pose 181]
  - [Pose 181, Pose 185]
  - [Pose 185, Pose 187]
  - [Pose 187, INT-B3]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
