logger_name: faraway_right_lane
edges:
  - [Pose 92, Pose 104]
  - [Pose 104, Pose 101]
  - [Pose 101, Pose 111]
  - [Pose 111, Pose 113]
  - [Pose 113, Pose 233]
  - [Pose 233, Pose 234]
  - [Pose 234, Pose 105]
  - [Pose 105, Pose 106]
  - [Pose 106, Pose 231]
  - [Pose 231, INT-B1]
  - [INT-B1, Pose 122]
  - [Pose 122, Pose 120]
  - [Pose 120, Pose 127]
  - [Pose 127, Pose 124]
  - [Pose 127, Pose 129]
  - [Pose 129, Pose 130]
  - [Pose 130, Pose 132]
  - [Pose 132, Pose 133]
  - [Pose 132, Pose 138]
  - [Pose 138, Pose 140]
  - [Pose 140, Pose 143]
  - [Pose 143, Pose 229]
  - [Pose 229, Pose 145]
  - [Pose 145, Pose 149]
  - [Pose 149, Pose 146]
  - [Pose 146, Pose 152]
  - [Pose 152, Pose 157]
  - [Pose 157, Pose 155]
  - [Pose 155, Pose 159]
  - [Pose 159, Pose 164]
  - [Pose 163, Pose 162]
  - [Pose 164, Pose 165]
  - [Pose 165, Pose 167]
  - [Pose 167, Pose 169]
  - [Pose 169, INT-B2]
  - [INT-B2, Pose 174]
  - [Pose 174, Pose 176]
  - [Pose 176, Pose 178]
  - [Pose 178, Pose 182]
  - [Pose 182, Pose 180]
  - [Pose 180, Pose 184]
  - [Pose 184, Pose 186]
  - [Pose 186, INT-B3]
  - [INT-B3, Pose 190]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
