logger_name: faraway_right_lane
edges:
  - [Pose_92, Pose_104]
  - [Pose_104, Pose_101]
  - [Pose_101, Pose_111]
  - [Pose_111, Pose_113]
  - [Pose_113, Pose_233]
  - [Pose_233, Pose_234]
  - [Pose_234, Pose_105]
  - [Pose_105, Pose_106]
  - [Pose_106, Pose_231]
  - [Pose_231, INT-B1]
  - [INT-B1, Pose_122]
  - [Pose_122, Pose_120]
  - [Pose_120, Pose_127]
  - [Pose_127, Pose_124]
  - [Pose_127, Pose_129]
  - [Pose_129, Pose_130]
  - [Pose_130, Pose_132]
  - [Pose_132, Pose_133]
  - [Pose_132, Pose_138]
  - [Pose_138, Pose_140]
  - [Pose_140, Pose_143]
  - [Pose_143, Pose_229]
  - [Pose_229, Pose_145]
  - [Pose_145, Pose_149]
  - [Pose_149, Pose_146]
  - [Pose_146, Pose_152]
  - [Pose_152, Pose_157]
  - [Pose_157, Pose_155]
  - [Pose_155, Pose_159]
  - [Pose_159, Pose_164]
  - [Pose_163, Pose_162]
  - [Pose_164, Pose_165]
  - [Pose_165, Pose_167]
  - [Pose_167, Pose_169]
  - [Pose_169, INT-B2]
  - [INT-B2, Pose_174]
  - [Pose_174, Pose_176]
  - [Pose_176, Pose_178]
  - [Pose_178, Pose_182]
  - [Pose_182, Pose_180]
  - [Pose_180, Pose_184]
  - [Pose_184, Pose_186]
  - [Pose_186, INT-B3]
  - [INT-B3, Pose_190]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
