logger_name: square_common_lane
edges:
  - [INT-C004, LC-036]
  - [LC-036, LC-037]
  - [LC-037, LC-038]
  - [LC-038, LC-039]
  - [INT-C005, INT-C009]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
