logger_name: square_left_lane
edges:
  - [D-C002, Pose 220]
  - [Pose 220, Pose 219]
  - [Pose 219, INT-C006]
  - [INT-C006, Pose 216]
  - [Pose 216, D-C007]
  - [D-C007, Pose 56]
  - [Pose 56, Pose 225]
  - [Pose 225, Pose 70]
  - [Pose 70, Pose 224]
  - [Pose 224, Pose 59]
  - [Pose 59, Pose 227]
  - [Pose 227, Pose 61]
  - [Pose 61, Pose 221]
  - [Pose 221, Pose 63]
  - [Pose 63, Pose 65]
  - [Pose 65, Pose 68]
  - [Pose 68, Pose 66]
  - [Pose 66, Pose 50]
  - [Pose 50, Pose 41]
  - [Pose 41, Pose 40]
  - [Pose 40, Pose 43]
  - [Pose 43, Pose 46]
  - [Pose 43, Pose 44]
  - [Pose 44, Pose 45]
  - [Pose 46, Pose 49]
  - [Pose 46, Pose 37]
  - [Pose 37, Pose 38]
  - [Pose 38, Pose 34]
  - [Pose 34, Pose 36]
  - [Pose 34, Pose 197]
  - [Pose 197, Pose 199]
  - [Pose 199, Pose 33]
  - [Pose 33, Pose 31]
  - [Pose 31, Pose 28]
  - [Pose 28, Pose 27]
  - [Pose 27, Pose 25]
  - [Pose 25, Pose 23]
  - [Pose 23, Pose 213]
  - [Pose 213, INT-C013]
  - [Pose 204, D-C017]
  - [Pose 205, Pose 206]
  - [Pose 206, Pose 208]
  - [Pose 208, Pose 207]
  - [Pose 207, D-C020]
  - [INT-C006, NC004]
  - [INT-C006, NC09]
  - [NC09, INT-C011]
  - [INT-C012, NC018]
  - [NC018, Pose 210]
  - [Pose 210, INT-C013]
  - [INT-C013, NC014]
  - [NC014, Pose 215]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
