logger_name: square_connection_lane
edges:
  - [D-C003, D-C002]
  - [Pose_218, Pose_219]
  - [Pose_217, Pose_216]
  - [D-C008, D-C007]
  - [Pose_57, Pose_56]
  - [Pose_226, Pose_225]
  - [Pose_58, Pose_70]
  - [Pose_223, Pose_224]
  - [Pose_69, Pose_59]
  - [Pose_228, Pose_227]
  - [Pose_222, Pose_61]
  - [Pose_60, Pose_221]
  - [Pose_62, Pose_63]
  - [Pose_64, Pose_65]
  - [Pose_71, Pose_68]
  - [Pose_67, Pose_66]
  - [Pose_41, Pose_42]
  - [Pose_38, Pose_39]
  - [Pose_36, Pose_35]
  - [Pose_197, Pose_196]
  - [Pose_199, Pose_198]
  - [Pose_33, Pose_32]
  - [Pose_31, Pose_30]
  - [Pose_28, Pose_29]
  - [Pose_27, Pose_26]
  - [Pose_25, Pose_24]
  - [Pose_23, Pose_22]
  - [Pose_213, Pose_212]
  - [NC014, Pose_214]
  - [Pose_215, NC015]
  - [D-C017, Pose_205]
  - [Pose_206, D-C016]
  - [Pose_208, Pose_203]
  - [D-C020, D-C021]
  - [NC09, NC10]
base_dir: 'angela'
event_radius: 0.3
event_threshold: 0.1
min_distance_static_samples: 0.5
