logger_name: square_connection_lane
edges:
  - [D-C003, D-C002]
  - [Pose 218, Pose 219]
  - [Pose 217, Pose 216]
  - [D-C008, D-C007]
  - [Pose 57, Pose 56]
  - [Pose 226, Pose 225]
  - [Pose 58, Pose 70]
  - [Pose 223, Pose 224]
  - [Pose 69, Pose 59]
  - [Pose 228, Pose 227]
  - [Pose 222, Pose 61]
  - [Pose 60, Pose 221]
  - [Pose 62, Pose 63]
  - [Pose 64, Pose 65]
  - [Pose 71, Pose 68]
  - [Pose 67, Pose 66]
  - [Pose 41, Pose 42]
  - [Pose 38, Pose 39]
  - [Pose 36, Pose 35]
  - [Pose 197, Pose 196]
  - [Pose 199, Pose 198]
  - [Pose 33, Pose 32]
  - [Pose 31, Pose 30]
  - [Pose 28, Pose 29]
  - [Pose 27, Pose 26]
  - [Pose 25, Pose 24]
  - [Pose 23, Pose 22]
  - [Pose 213, Pose 212]
  - [NC014, Pose 214]
  - [Pose 215, NC015]
  - [D-C017, Pose 205]
  - [Pose 206, D-C016]
  - [Pose 208, Pose 203]
  - [D-C020, D-C021]
  - [NC09, NC10]
base_dir: 'angela'
event_radius: 0.3
event_threshold: 0.1
min_distance_static_samples: 0.5
