logger_name: square_left_lane
edges:
  - [D-C002, Pose_220]
  - [Pose_220, Pose_219]
  - [Pose_219, INT-C006]
  - [INT-C006, Pose_216]
  - [Pose_216, D-C007]
  - [D-C007, Pose_56]
  - [Pose_56, Pose_225]
  - [Pose_225, Pose_70]
  - [Pose_70, Pose_224]
  - [Pose_224, Pose_59]
  - [Pose_59, Pose_227]
  - [Pose_227, Pose_61]
  - [Pose_61, Pose_221]
  - [Pose_221, Pose_63]
  - [Pose_63, Pose_65]
  - [Pose_65, Pose_68]
  - [Pose_68, Pose_66]
  - [Pose_66, Pose_50]
  - [Pose_50, Pose_41]
  - [Pose_41, Pose_40]
  - [Pose_40, Pose_43]
  - [Pose_43, Pose_46]
  - [Pose_43, Pose_44]
  - [Pose_44, Pose_45]
  - [Pose_46, Pose_49]
  - [Pose_46, Pose_37]
  - [Pose_37, Pose_38]
  - [Pose_38, Pose_34]
  - [Pose_34, Pose_36]
  - [Pose_34, Pose_197]
  - [Pose_197, Pose_199]
  - [Pose_199, Pose_33]
  - [Pose_33, Pose_31]
  - [Pose_31, Pose_28]
  - [Pose_28, Pose_27]
  - [Pose_27, Pose_25]
  - [Pose_25, Pose_23]
  - [Pose_23, Pose_213]
  - [Pose_213, INT-C013]
  - [Pose_204, D-C017]
  - [Pose_205, Pose_206]
  - [Pose_206, Pose_208]
  - [Pose_208, Pose_207]
  - [Pose_207, D-C020]
  - [INT-C006, NC004]
  - [INT-C006, NC09]
  - [NC09, INT-C011]
  - [INT-C012, NC018]
  - [NC018, Pose_210]
  - [Pose_210, INT-C013]
  - [INT-C013, NC014]
  - [NC014, Pose_215]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
