logger_name: square_right_lane
edges:
- [D-C003, Pose 220]
- [Pose 220 , Pose 218]
- [Pose 218 , INT-C006]
- [INT-C006, Pose 217]
- [Pose 217 , D-C008]
- [D-C008 , Pose 57]
- [Pose 57 , Pose 226]
- [Pose 226 , Pose 58]
- [Pose 58, Pose 223]
- [Pose 223 , Pose 69]
- [Pose 69 , Pose 228]
- [Pose 228, Pose 222]
- [Pose 222 , Pose 60]
- [Pose 60, Pose 62]
- [Pose 62 , Pose 64]
- [Pose 64 , Pose 71]
- [Pose 71, Pose 67]
- [Pose 67, Pose 50]
- [Pose 50, Pose 42]
- [Pose 42, Pose 40]
- [Pose 40, Pose 47]
- [Pose 47, Pose 48]
- [Pose 48, Pose 37]
- [Pose 37, Pose 39]
- [Pose 39, Pose 34]
- [Pose 34, Pose 35]
- [Pose 34, Pose 196]
- [Pose 196, Pose 198]
- [Pose 198, Pose 32]
- [Pose 32, Pose 30]
- [Pose 30, Pose 29]
- [Pose 29, Pose 26]
- [Pose 26, Pose 24]
- [Pose 24, Pose 22]
- [Pose 22, Pose 212]
- [Pose 212, INT-C013]
- [Pose 204, Pose 205]
- [Pose 205, D-C016]
- [D-C016, Pose 203]
- [Pose 203 , Pose 207]
- [Pose 207, D-C021]
- [INT-C006 , NC005]
- [INT-C006 , NC10]
- [NC10 , INT-C011]
- [INT-C012 , NC019]
- [NC019, Pose 211]
- [Pose 211 , INT-C013]
- [INT-C013 , Pose 214]
- [Pose 214 , NC015]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
