logger_name: square_right_lane
edges:
- [D-C003, Pose_220]
- [Pose_220 , Pose_218]
- [Pose_218 , INT-C006]
- [INT-C006, Pose_217]
- [Pose_217 , D-C008]
- [D-C008 , Pose_57]
- [Pose_57 , Pose_226]
- [Pose_226 , Pose_58]
- [Pose_58, Pose_223]
- [Pose_223 , Pose_69]
- [Pose_69 , Pose_228]
- [Pose_228, Pose_222]
- [Pose_222 , Pose_60]
- [Pose_60, Pose_62]
- [Pose_62 , Pose_64]
- [Pose_64 , Pose_71]
- [Pose_71, Pose_67]
- [Pose_67, Pose_50]
- [Pose_50, Pose_42]
- [Pose_42, Pose_40]
- [Pose_40, Pose_47]
- [Pose_47, Pose_48]
- [Pose_48, Pose_37]
- [Pose_37, Pose_39]
- [Pose_39, Pose_34]
- [Pose_34, Pose_35]
- [Pose_34, Pose_196]
- [Pose_196, Pose_198]
- [Pose_198, Pose_32]
- [Pose_32, Pose_30]
- [Pose_30, Pose_29]
- [Pose_29, Pose_26]
- [Pose_26, Pose_24]
- [Pose_24, Pose_22]
- [Pose_22, Pose_212]
- [Pose_212, INT-C013]
- [Pose_204, Pose_205]
- [Pose_205, D-C016]
- [D-C016, Pose_203]
- [Pose_203 , Pose_207]
- [Pose_207, D-C021]
- [INT-C006 , NC005]
- [INT-C006 , NC10]
- [NC10 , INT-C011]
- [INT-C012 , NC019]
- [NC019, Pose_211]
- [Pose_211 , INT-C013]
- [INT-C013 , Pose_214]
- [Pose_214 , NC015]
base_dir: 'angela'
event_radius: 1
event_threshold: 0.1
min_distance_static_samples: 0.5
